### ISSUE TITLE
GIT bach issue EPG 

### ISSUE THREAD

**Issue by kareemelmasry** [iptv-org/epg#2119]
### Description

Kareemelmasry@Kareemlap MINGW64 ~/epg (master)
$ npm install

up to date, audited 754 packages in 6s

94 packages are looking for funding
  run `npm fund` for details

26 vulnerabilities (22 moderate, 4 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

Kareemelmasry@Kareemlap MINGW64 ~/epg (master)
$ set SITE=beinsports.com&& npm run grab

> grab
> cross-var epg-grabber --config=sites/$SITE/$SITE.config.js --channels=sites/$SITE/$SITE.channels.xml --output=guides/{lang}/{site}.xml

Starting...
Loading 'sites/$SITE/$SITE.config.js'...
node:internal/modules/cjs/loader:1072
  const err = new Error(message);
              ^

Error: Cannot find module 'C:\Users\Kareemelmasryy\epg\sites\$SITE\$SITE.config.js'
Require stack:
- C:\Users\Kareemelmasryy\epg\node_modules\epg-grabber\bin\epg-grabber.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1072:15)
    at Module._load (node:internal/modules/cjs/loader:925:27)
    at Module.require (node:internal/modules/cjs/loader:1139:19)
    at require (node:internal/modules/helpers:121:18)
    at main (C:\Users\Kareemelmasryy\epg\node_modules\epg-grabber\bin\epg-grabber.js:54:16)
    at Object.<anonymous> (C:\Users\Kareemelmasryy\epg\node_modules\epg-grabber\bin\epg-grabber.js:157:1)
    at Module._compile (node:internal/modules/cjs/loader:1257:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1311:10)
    at Module.load (node:internal/modules/cjs/loader:1115:32)
    at Module._load (node:internal/modules/cjs/loader:962:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Kareemelmasryy\\epg\\node_modules\\epg-grabber\\bin\\epg-grabber.js'
  ]
}

Node.js v20.3.1

Kareemelmasry@Kareemlap MINGW64 ~/epg (master)
$

**Comment by YassineElbouchaibi** [comment]
I feel like you are using git bash from your prompts, sample output and issue title in which case here are a couple ways to execute the program.

Inline set SITE and execute grabber:
```sh
$ SITE=beinsports.com npm run grab
```

Export first and then execute grabber:
```sh
$ export SITE=beinsports.com
$ npm run grab
```

**Comment by kareemelmasry** [comment]
Kareemelmasry@Kareemlap MINGW64 ~
$ git clone --depth 1 -b master https://github.com/iptv-org/epg.git
fatal: destination path 'epg' already exists and is not an empty directory.

Kareemelmasry@Kareemlap MINGW64 ~
$ cd epg

Kareemelmasry@Kareemlap MINGW64 ~/epg (master)
$ npm install

up to date, audited 754 packages in 5s

94 packages are looking for funding
  run `npm fund` for details

26 vulnerabilities (22 moderate, 4 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

Kareemelmasry@Kareemlap MINGW64 ~/epg (master)
$ $ SITE=beinsports.com npm run grab
bash: $: command not found

Kareemelmasry@Kareemlap MINGW64 ~/epg (master)
$ SITE=beinsports.com npm run grab

> grab
> cross-var epg-grabber --config=sites/$SITE/$SITE.config.js --channels=sites/$SITE/$SITE.channels.xml --output=guides/{lang}/{site}.xml

Starting...
Loading 'sites/beinsports.com/beinsports.com.config.js'...
Loading 'sites/beinsports.com/beinsports.com.channels.xml'...
node:fs:592
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open 'C:\Users\Kareemelmasryy\epg\sites\beinsports.com\beinsports.com.channels.xml'
    at Object.openSync (node:fs:592:3)
    at Object.readFileSync (node:fs:460:35)
    at Object.read (C:\Users\Kareemelmasryy\epg\node_modules\epg-grabber\src\file.js:13:13)
    at main (C:\Users\Kareemelmasryy\epg\node_modules\epg-grabber\bin\epg-grabber.js:77:28)
    at Object.<anonymous> (C:\Users\Kareemelmasryy\epg\node_modules\epg-grabber\bin\epg-grabber.js:157:1)
    at Module._compile (node:internal/modules/cjs/loader:1257:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1311:10)
    at Module.load (node:internal/modules/cjs/loader:1115:32)
    at Module._load (node:internal/modules/cjs/loader:962:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\Users\\Kareemelmasryy\\epg\\sites\\beinsports.com\\beinsports.com.channels.xml'
}

Node.js v20.3.1

Kareemelmasry@Kareemlap MINGW64 ~/epg (master)
$ export SITE=beinsports.com

Kareemelmasry@Kareemlap MINGW64 ~/epg (master)
$ npm run grab

> grab
> cross-var epg-grabber --config=sites/$SITE/$SITE.config.js --channels=sites/$SITE/$SITE.channels.xml --output=guides/{lang}/{site}.xml

Starting...
Loading 'sites/beinsports.com/beinsports.com.config.js'...
Loading 'sites/beinsports.com/beinsports.com.channels.xml'...
node:fs:592
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open 'C:\Users\Kareemelmasryy\epg\sites\beinsports.com\beinsports.com.channels.xml'
    at Object.openSync (node:fs:592:3)
    at Object.readFileSync (node:fs:460:35)
    at Object.read (C:\Users\Kareemelmasryy\epg\node_modules\epg-grabber\src\file.js:13:13)
    at main (C:\Users\Kareemelmasryy\epg\node_modules\epg-grabber\bin\epg-grabber.js:77:28)
    at Object.<anonymous> (C:\Users\Kareemelmasryy\epg\node_modules\epg-grabber\bin\epg-grabber.js:157:1)
    at Module._compile (node:internal/modules/cjs/loader:1257:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1311:10)
    at Module.load (node:internal/modules/cjs/loader:1115:32)
    at Module._load (node:internal/modules/cjs/loader:962:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\Users\\Kareemelmasryy\\epg\\sites\\beinsports.com\\beinsports.com.channels.xml'
}

Node.js v20.3.1

Kareemelmasry@Kareemlap MINGW64 ~/epg (master)
$

**Comment by kareemelmasry** [comment]
acually can't find the directory called guides in the epg directory and can't get or find the epg files.

**Comment by kareemelmasry** [comment]
acually can't find the directory called guides in the epg directory and can't get or find the epg files.

**Comment by YassineElbouchaibi** [comment]
You have fixed your original problem as you are now able to run the program with the SITE variable injected. This is a different issue that is open here: https://github.com/iptv-org/epg/issues/2122
