### ISSUE TITLE
Sites that don't respect the `sites/${site}/${site}.channels.xml` pattern fail.

### ISSUE THREAD

**Issue by YassineElbouchaibi** [iptv-org/epg#2122]
Sites that don't respect the `sites/${site}/${site}.channels.xml` pattern like https://github.com/iptv-org/epg/tree/master/sites/beinsports.com will not work using the `npm run grab` script as some sites have `_{lang}` suffixes.

e.g.
<img width="381" alt="image" src="https://github.com/iptv-org/epg/assets/46449697/cf87a909-b56b-4d03-b778-648d8e76cc50">

Error:
```
Error: ENOENT: no such file or directory, open '/epg/sites/beinsports.com/beinsports.com.channels.xml'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
    at Object.read (/epg/node_modules/epg-grabber/src/file.js:13:13)
    at main (/epg/node_modules/epg-grabber/bin/epg-grabber.js:77:28)
    at Object.<anonymous> (/epg/node_modules/epg-grabber/bin/epg-grabber.js:157:1)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/epg/sites/beinsports.com/beinsports.com.channels.xml'
}
```

**Comment by freearhey** [comment]
Good point! This will have to be fixed.
