### ISSUE TITLE
Guide Error

### ISSUE THREAD

**Issue by DumberSoft** [iptv-org/epg#2139]
### Site

tv.movistar.com.pe

### Description

Starting...
Loading 'sites/tv.movistar.com.pe/tv.movistar.com.pe.config.js'...
(node:16718) UnhandledPromiseRejectionWarning: /var/www/html/epg/sites/tv.movistar.com.pe/tv.movistar.com.pe.config.js:46
  return item.Images?.VideoFrame?.[0]?.Url
                     ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at main (/var/www/html/epg/node_modules/epg-grabber/bin/epg-grabber.js:54:16)
    at Object.<anonymous> (/var/www/html/epg/node_modules/epg-grabber/bin/epg-grabber.js:157:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
(node:16718) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16718) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by PopeyeTheSai10r** [comment]
The config still working for me.

Can you please share what command you are using to start the grabber?

**Comment by DumberSoft** [comment]
Linux

SITE=tv.movistar.com.pe npm run grab

**Comment by DumberSoft** [comment]
root@vmi1354233:~/epg# SITE=tv.movistar.com.pe npm run grab

> epg@ grab /root/epg
> cross-var epg-grabber --config=sites/$SITE/$SITE.config.js --channels=sites/$SITE/$SITE.channels.xml --output=guides/{lang}/{site}.xml

Starting...
Loading 'sites/tv.movistar.com.pe/tv.movistar.com.pe.config.js'...
(node:188345) UnhandledPromiseRejectionWarning: /root/epg/sites/tv.movistar.com.pe/tv.movistar.com.pe.config.js:46
  return item.Images?.VideoFrame?.[0]?.Url
                     ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at main (/root/epg/node_modules/epg-grabber/bin/epg-grabber.js:54:16)
    at Object.<anonymous> (/root/epg/node_modules/epg-grabber/bin/epg-grabber.js:157:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
(node:188345) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:188345) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
root@vmi1354233:~/epg#

**Comment by PopeyeTheSai10r** [comment]
Try running 
`npx epg-grabber --config=sites/tv.movistar.com.pe/tv.movistar.com.pe.config.js --channels=sites/tv.movistar.com.pe/tv.movistar.com.pe.channels.xml --output=guide.xml --days=1`

**Comment by Hoang797** [comment]
npx epg-grabber --config=sites/tv.movistar.com.pe/tv.movistar.com.pe.config.js --channels=sites/tv.movistar.com.pe/tv.movistar.com.pe.channels.xml --output=guide.xml --days=1

—

**Comment by PopeyeTheSai10r** [comment]
Did the output change?

**Comment by freearhey** [comment]
This config works fine for me too.

If the problem is still there try to run the "grabber" using the new command:

```sh
npm run grab -- --site=tv.movistar.com.pe
```
