### ISSUE TITLE
when run SET=tv.cctv.com npm run grab, npm is borken

### ISSUE THREAD

**Issue by wx2020** [iptv-org/epg#2150]
### Site

tv.cctv.com

### Description

Error: Cannot find module '/root/workplace/epg/sites/.config.js'
Require stack:
- /root/workplace/epg/node_modules/epg-grabber/bin/epg-grabber.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1047:15)
    at Module._load (node:internal/modules/cjs/loader:893:27)
    at Module.require (node:internal/modules/cjs/loader:1113:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at main (/root/workplace/epg/node_modules/epg-grabber/bin/epg-grabber.js:54:16)
    at Object.<anonymous> (/root/workplace/epg/node_modules/epg-grabber/bin/epg-grabber.js:157:1)
    at Module._compile (node:internal/modules/cjs/loader:1226:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1280:10)
    at Module.load (node:internal/modules/cjs/loader:1089:32)
    at Module._load (node:internal/modules/cjs/loader:930:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/root/workplace/epg/node_modules/epg-grabber/bin/epg-grabber.js' ]
}

**Comment by digitalp** [comment]
Same issue here.

**Comment by dutchdevil-83** [comment]
same here... how to solve?

**Comment by freearhey** [comment]
Try to run it using this command:

```sh
npm run grab -- --site=tv.cctv.com
```
