### ISSUE TITLE
sky.com epg channel list refresh error

### ISSUE THREAD

**Issue by purplescorpion1** [iptv-org/epg#2352]
### Site

sky.com

### Description

When trying to update channel list from sky.com (https://github.com/iptv-org/epg/tree/master/sites/sky.com) I get the following error

A number of channels either don't exist (404) or have been renamed so a new channel list is required

```
npm run channels:parse -- --config=./sites/sky.com/sky.com.config.js --output=./sites/sky.com/sky.com.channels.xml

> channels:parse
> npx tsx scripts/commands/channels/parse.ts --config=./sites/sky.com/sky.com.config.js --output=./sites/sky.com/sky.com.channels.xml

(node:26828) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("file%3A///C%3A/AI/epg/node_modules/tsx/dist/loader.mjs", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:26828) UnsupportedWarning: `globalPreload` has been removed; use `initialize` instead.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:26828) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.

C:\***\sites\sky.com\sky.com.config.js:42
    initialData.state.epgData.channelsForRegion.forEach(item => {
                                                ^
TypeError: Cannot read properties of undefined (reading 'forEach')
    at Object.channels (C:\***\sites\sky.com\sky.com.config.js:42:49)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at main (C:\***\scripts\commands\channels\parse.ts:50:22)
```

**Comment by purplescorpion1** [comment]
just noticed also mentioned
https://github.com/iptv-org/epg/issues/2325

**Comment by freearhey** [comment]
Closed in favor of https://github.com/iptv-org/epg/issues/2325
