### ISSUE TITLE
ziggogo.tv

### ISSUE THREAD

**Issue by freearhey** [iptv-org/epg#2393]
### Site

ziggogo.tv

### Description

Test failed:

```sh
npm test -- ziggogo.tv

> test
> run-script-os ziggogo.tv


> test:default
> TZ=Pacific/Nauru npx jest --runInBand ziggogo.tv

 FAIL  sites/ziggogo.tv/ziggogo.tv.test.js
  ✕ can generate valid url (13 ms)
  ✕ can parse response (19 ms)
  ✓ can handle empty guide (1 ms)

  ● can generate valid url

    expect(received).toBe(expected) // Object.is equality

    Expected: "https://static.spark.ziggogo.tv/eng/web/epg-service-lite/nl/nl/events/segments/20221028000000"
    Received: "https://static.spark.ziggogo.tv/eng/web/epg-service-lite/nl/en/events/segments/20221028000000"

      19 |
      20 | it('can generate valid url', () => {
    > 21 |   expect(url({ date, channel })).toBe(
         |                                  ^
      22 |     'https://static.spark.ziggogo.tv/eng/web/epg-service-lite/nl/nl/events/segments/20221028000000'
      23 |   )
      24 | })

      at Object.<anonymous> (sites/ziggogo.tv/ziggogo.tv.test.js:21:34)

  ● can parse response

    expect(received).toMatchObject(expected)

    - Expected  - 15
    + Received  +  3

      Object {
    -   "actors": Array [
    -     "Malou Petter",
    -     "Mark Visser",
    -     "Rob Trip",
    -     "Jeroen Overbeek",
    -     "Simone Weimans",
    -     "Annechien Steenhuizen",
    -     "Jeroen Tjepkema",
    -     "Saïda Maggé",
    -     "Winfried Baijens",
    -   ],
    -   "category": Array [
    -     "Nieuws",
    -   ],
    -   "description": "Met het laatste nieuws, gebeurtenissen van nationaal en internationaal belang en de weersverwachting voor de avond en komende dagen.",
    +   "actors": undefined,
    +   "category": undefined,
    +   "description": undefined,
        "start": "2022-10-27T23:40:00.000Z",
        "stop": "2022-10-28T00:07:00.000Z",
        "title": "NOS Journaal",
      }

      68 |   })
      69 |
    > 70 |   expect(results[0]).toMatchObject({
         |                      ^
      71 |     start: '2022-10-27T23:40:00.000Z',
      72 |     stop: '2022-10-28T00:07:00.000Z',
      73 |     title: 'NOS Journaal',

      at Object.<anonymous> (sites/ziggogo.tv/ziggogo.tv.test.js:70:22)

Test Suites: 1 failed, 1 total
Tests:       2 failed, 1 passed, 3 total
Snapshots:   0 total
Time:        3.34 s
Ran all test suites matching /ziggogo.tv/i.
```

**Comment by BellezaEmporium** [comment]
I'm currently working on it, but the "journaal" part in the test could be because of the fact we make one more request to get the details of the program in another variable, named "detail". The test doesn't see that and just tries to load... nothing, most certainly.

**Comment by BellezaEmporium** [comment]
Believe it or not... the issue was in "getProgramDetails". Axios didn't manage to load the data properly, however fetch (native node fetch) did the trick.
