### ISSUE TITLE
Error: Cannot find module '@freearhey/core'

### ISSUE THREAD

**Issue by TridentWorks** [iptv-org/epg#2448]
Followed the install instructions. This is the error I get when trying to run  "nmp run grab". Grab.ts is located where it is suppose to be. If I missed something please let me know then delete this.

OS Version: Kubuntu 24.04.1 LTS x86_64
Kernel: 6.8.0-45-lowlatency
Node.js v18.19.1

test:~/epg$ sudo apt install npm
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
npm is already the newest version (9.2.0~ds1-2).
0 upgraded, 0 newly installed, 0 to remove.

test:~/epg$ sudo npm run grab -- --https://www.9tv.co.il/BroadcastSchedule

> grab
> npx tsx scripts/commands/epg/grab.ts --https://www.9tv.co.il/BroadcastSchedule

node:internal/modules/cjs/loader:1134
  const err = new Error(message);
              ^

Error: Cannot find module '@freearhey/core'
Require stack:
- /home/test/epg/scripts/commands/epg/grab.ts
    at Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)
    at nextResolveSimple (/root/.npm/_npx/fd45a72a545557e9/node_modules/tsx/dist/register-DpmFHar1.cjs:3:942)
    at /root/.npm/_npx/fd45a72a545557e9/node_modules/tsx/dist/register-DpmFHar1.cjs:2:2550
    at /root/.npm/_npx/fd45a72a545557e9/node_modules/tsx/dist/register-DpmFHar1.cjs:2:1624
    at resolveTsPaths (/root/.npm/_npx/fd45a72a545557e9/node_modules/tsx/dist/register-DpmFHar1.cjs:3:760)
    at /root/.npm/_npx/fd45a72a545557e9/node_modules/tsx/dist/register-DpmFHar1.cjs:3:1038
    at m._resolveFilename (file:///root/.npm/_npx/fd45a72a545557e9/node_modules/tsx/dist/register-Swi4xIvk.mjs:1:789)
    at Module._load (node:internal/modules/cjs/loader:975:27)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/test/epg/scripts/commands/epg/grab.ts' ]
}

Node.js v18.19.1

test@:~/epg/scripts/commands/epg$ ls -a
.  ..  grab.ts

**Comment by ffalor** [comment]
run `npm install` first

**Comment by PopeyeTheSai10r** [comment]
> run `npm install` first

@TridentWorks
