### ISSUE TITLE
Error when running npm run grab site=example.com command

### ISSUE THREAD

**Issue by MyAlchemicalRomance** [iptv-org/epg#2449]
### Describe your issue

While running the command to grab EPG at a specific site, powershell returns with the following error:
> grab
> npx tsx scripts/commands/epg/grab.ts

TypeError: Cannot destructure property 'port' of 'undefined' as it is undefined.
    at B (file:///D:/Downloads/Software/Jellyfin/epg/node_modules/tsx/dist/loaders-deprecated-261ba186.mjs:1:1472)
    at Hooks.addCustomLoader (node:internal/modules/esm/hooks:183:24)
    at Hooks.register (node:internal/modules/esm/hooks:157:16)
    at initializeHooks (node:internal/modules/esm/utils:317:5)
    at customizedModuleWorker (node:internal/modules/esm/worker:109:13)

**Comment by MyAlchemicalRomance** [comment]
> ### Describe your issue
> While running the command to grab EPG at a specific site, powershell returns with the following error:
> 
> > grab
> > npx tsx scripts/commands/epg/grab.ts
> 
> TypeError: Cannot destructure property 'port' of 'undefined' as it is undefined. at B (file:///D:/Downloads/Software/Jellyfin/epg/node_modules/tsx/dist/loaders-deprecated-261ba186.mjs:1:1472) at Hooks.addCustomLoader (node:internal/modules/esm/hooks:183:24) at Hooks.register (node:internal/modules/esm/hooks:157:16) at initializeHooks (node:internal/modules/esm/utils:317:5) at customizedModuleWorker (node:internal/modules/esm/worker:109:13)

Found out that my node version was not supported, restarted everything with the latest stable version and managed to stop getting the previous error. Now, I'm facing new errors:


D:\Downloads\Software\Jellyfin\epg>npm run grab --site=beinsports.com

> grab
> npx tsx scripts/commands/epg/grab.ts

(node:10844) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("file%3A///D%3A/Downloads/Software/Jellyfin/epg/node_modules/tsx/dist/loader.mjs", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)

D:\Downloads\Software\Jellyfin\epg\scripts\commands\epg\grab.ts:51
    throw new Error('One of the arguments must be presented: `--site` or `--channels`')
          ^
Error: One of the arguments must be presented: `--site` or `--channels`
    at main (D:\Downloads\Software\Jellyfin\epg\scripts\commands\epg\grab.ts:51:11)
    at D:\Downloads\Software\Jellyfin\epg\scripts\commands\epg\grab.ts:96:1
    at Object.<anonymous> (D:\Downloads\Software\Jellyfin\epg\scripts\commands\epg\grab.ts:3:3)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Object.S (D:\Downloads\Software\Jellyfin\epg\node_modules\tsx\dist\cjs\index.cjs:1:1250)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1104:12)
    at cjsLoader (node:internal/modules/esm/translators:346:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:286:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:234:25)

**Comment by MyAlchemicalRomance** [comment]
. Now, I'm facing new errors:
> 
> D:\Downloads\Software\Jellyfin\epg>npm run grab --site=beinsports.com

Nevermind, figured out what was wrong: 

npm run grab **--** --site=beinsports.com
